"""Per-mod compatibility matrix (report only; applies nothing).

Usage: python tools/compat_report.py [--md docs/COMPATIBILITY.md]
"""
import argparse
import collections
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from modkit import classify_blocks, parse_mod, read_archive  # noqa: E402
from modkit.match import EMPTY, MULTI, NONE, ONE, WS  # noqa: E402

COLS = [ONE, MULTI, WS, NONE, EMPTY]
SHORT = {ONE: "exact 1", MULTI: "exact >1", WS: "ws-only", NONE: "missing", EMPTY: "empty"}


def verdict(c, total):
    if total == 0:
        return "NO BLOCKS PARSED"
    if c[ONE] + c[MULTI] == total:
        return "all blocks match exactly"
    if c[ONE] + c[MULTI] == 0:
        return "no blocks match"
    return "PARTIAL (would be partially applied by KittyPatcher)"


def build(archive="Mods.zip", game="CourseOfTemptation.html"):
    r = read_archive(archive)
    text = Path(game).read_text(encoding="utf-8")
    lines = [
        "# Compatibility matrix (diagnostic, exact matching against original game)",
        "",
        "Generated by `tools/compat_report.py`. Report only: nothing is applied or excluded here.",
        "\"Missing\" blocks may still match text created by another mod (order-dependent); not simulated.",
        "Gameplay and save compatibility unverified.",
        "",
        "| Mod | Format | Blocks | " + " | ".join(SHORT[c] for c in COLS) + " | Verdict | Notes |",
        "|---|---|---|" + "---|" * len(COLS) + "---|---|",
    ]
    totals = collections.Counter()
    verdicts = collections.Counter()
    for m in r.mods:
        blocks, notes = parse_mod(m)
        res, _ = classify_blocks(blocks, text)
        c = collections.Counter(cat for _, cat, _ in res)
        totals.update(c)
        v = verdict(c, len(blocks))
        verdicts[v] += 1
        fmts = ",".join(sorted({b.fmt for b in blocks})) or "-"
        if not m.lowercase_extension:
            notes = notes + ["uppercase extension; KittyPatcher v0.1.2 source skips it"]
        lines.append(
            f"| `{m.path.split('/', 1)[-1]}` | {fmts} | {len(blocks)} | "
            + " | ".join(str(c[k]) for k in COLS)
            + f" | {v} | {'; '.join(notes)} |")
    lines += ["", "## Totals", ""]
    lines += [f"- {SHORT[k]}: {totals[k]}" for k in COLS]
    lines += [f"- {k}: {n} mods" for k, n in sorted(verdicts.items())]
    for i in r.issues:
        lines.append(f"- {i.severity}: `{i.path}`: {i.message}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--md")
    a = ap.parse_args()
    out = build()
    if a.md:
        Path(a.md).write_text(out, encoding="utf-8")
    else:
        sys.stdout.write(out)
